#!/usr/bin/env python3
"""Migrate the legacy org/roam folder into the Denote KB layout.

    kb/migrate.py SRC OUT

SRC is the untouched legacy folder (e.g. ~/data/org-mode-backup); OUT must not exist.  The legacy
`org/` and `roam/` directories are copied along unchanged (the two-week trial keeps them).  Every new note
is created with `kb new --created ...` so its ID and #+date show when the content was created, not when
the migration ran.  Creation time, per source:
  roam notes       the timestamp in the file name
  roam dailies     the date in the file name
  org/ files       earliest date found in the text (2015 .. today), else the file's mtime
  generated notes  (Logistics backlog, the grouping inbox note) now
Decisions encoded here are listed below.
"""
import datetime, glob, os, re, shutil, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
KB = os.path.join(HERE, "kb")

# --- decisions --------------------------------------------------------------------------------------
ROAM_WORK = {"sapi", "shipping_calculator", "shipping_options", "shipdate", "quoter_dll", "plan_finder"}
PERSONS = ("adam ksenia stepan michal denis daniel gary vincent mykola suruchi nick piero inaki vlad "
           "vladyslav asli grand").split()
# (file, title, tags).  Imported whole; the open tasks are moved out afterwards.
REFERENCES = [
    ("default", "Default notes", "reference,work"), ("refile", "Refile notes", "reference,work"),
    ("security-summit", "Security summit", "reference,work"),
    ("self-assessment", "Self assessment", "reference,work"),
    ("shell-presentation", "Shell presentation", "reference"),
    ("jak-funguje-tls", "Jak funguje TLS", "reference"), ("interviews", "Interviews", "reference,work"),
    ("squad-leads", "Squad leads", "reference,work"), ("work", "Work notes", "reference,work"),
    ("mobile", "Mobile notes", "reference,work"), ("projekty", "Projekty", "reference,personal"),
    ("health", "Health", "reference,personal"),
]
# Source lines whose weekday does not match their date (kb refuses those); the date is kept.
WEEKDAY_FIXES = {"refile": ("SCHEDULED: <2024-04-02 Fri>", "SCHEDULED: <2024-04-02 Tue>"),
                 "projekty": ("[2026-02-11 Sat 12:56]", "[2026-02-11 Wed 12:56]")}
# Open tasks, matched by the start of the heading: (note key, heading prefix) -> project note or tasks.org
BACKLOG_TASKS = [("refile", p) for p in (
    "mail Re: Transit", "investigate if v6", "ask erin", "check access to sa-labe", "status of debug url",
    "figure how to do AI", "clean up nest js", "look into react scan", "start labe bughung",
    "run through e2e")] + [("work", "book rooms")]
TASKS_ORG = [("refile", "GitHub - zkry"), ("refile", "Help spread the knowledge"),
             ("mobile", "Update GitHub token"), ("mobile", "Najít únikovou"), ("health", "Exercise"),
             ("health", "Tracked exercise"), ("projekty", "zkusit namodelovat"),
             ("projekty", "kontrola znaminek"), ("projekty", "ockovani"), ("projekty", "Daily diary"),
             ("default", "Twitch prime"), ("refile", "tldr pages")]
# Not imported: generated by beorg, empty, test entries, or notifications (gitlab).
DROPPED = ("calendar-beorg reminders-beorg notes todo new-tryout shopping ash doma gitlab").split()
TO_ARCHIVE = {"archive": "archive-2018.org", "daily": "daily-2022.org"}   # -> archive/legacy/
GROUPS = [  # inbox note: proposed grouping of the roam notes (matched in this order)
    ("Shipping (work)", r"^(shipping|sapi$|lounge|plan finder|quoter|shipdate)"),
    ("Emacs & org-mode", r"emacs|elisp|org|doom|flycheck|hyperbole|zettel|transient|vim|viper|guix|calc"),
    ("Security & OSINT", r"hack|shell|privilege|osint|reverse|burp|certificate|gpg|security|orca|summit|csp"),
    ("Homelab & Kubernetes", r"homelab|kube|kustom|talos|synology|raspberry|wsl"),
    ("Programming & web", r"go|javascript|react|html|frontend|programming|value|http|jujutsu|claude|building"),
]

# --- helpers ------------------------------------------------------------------------------------------
today = datetime.datetime.now()


def kb(*args, env=None, ok=False):
    r = subprocess.run([KB, *args], capture_output=True, text=True, stdin=subprocess.DEVNULL, env=env)
    if r.returncode and not ok:
        sys.exit("kb %s failed:\n%s%s" % (" ".join(args[:3]), r.stdout, r.stderr))
    return r.stdout.strip()


def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def strip_title(s):
    m = re.match(r"\s*#\+title:\s*(.*)\n", s, re.I)
    return (m.group(1).strip() if m else None), (s[m.end():] if m else s).lstrip("\n")


def earliest(text, path):
    """Earliest plausible date in TEXT as 'YYYY-MM-DD[ HH:MM]'; falls back to PATH's mtime."""
    found = []
    pats = [r"[<\[](\d{4})-(\d\d)-(\d\d)(?: [A-Za-z]{2,3}\.?)?(?: (\d\d):(\d\d))?",
            r"^\*+ (\d{4})-(\d\d)-(\d\d)()()\b"]
    for pat in pats:
        for m in re.finditer(pat, text, re.M):
            y, mo, d, h, mi = m.groups()
            try:
                t = datetime.datetime(int(y), int(mo), int(d), int(h or 0), int(mi or 0))
            except ValueError:
                continue
            if datetime.datetime(2015, 1, 1) <= t <= today:
                found.append((t, bool(h)))
    if found:
        t, has_time = min(found)
    else:
        t, has_time = datetime.datetime.fromtimestamp(os.stat(path).st_mtime), True
    return t.strftime("%Y-%m-%d %H:%M") if has_time else t.strftime("%Y-%m-%d")


def new_note(root, kind, title, tags, body, created):
    args = ["new", kind, title, "--tags", tags, "--body", body]
    if created:
        args += ["--created", created]
    return kb(*args)


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src, out = (os.path.abspath(os.path.expanduser(p)) for p in sys.argv[1:])
    if os.path.exists(out):
        sys.exit("OUT %s already exists" % out)
    shutil.copytree(src, out, ignore=shutil.ignore_patterns(".git", ".stfolder"))
    shutil.copytree(os.path.join(HERE, "template"), out, dirs_exist_ok=True)
    os.environ["KB_ROOT"] = out
    os.chdir(out)
    report = {"roam": 0, "dailies": 0, "persons": 0, "references": 0}

    # 1. roam notes: ID = the roam file's own timestamp, links converted in a second pass
    mapping, roam_rows = {}, []
    for f in sorted(glob.glob(os.path.join(src, "roam", "*.org"))):
        s = read(f)
        m = re.match(r":PROPERTIES:\n:ID:\s+(\S+)\n:END:\n", s)
        uid = m.group(1)
        title, body = strip_title(s[m.end():])
        name = os.path.basename(f)
        ts = re.match(r"(\d{4})(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)-(.*)\.org$", name)
        key = ts.group(7)
        created = "%s-%s-%s %s:%s:%s" % ts.group(1, 2, 3, 4, 5, 6)
        tags = "reference,work" if key in ROAM_WORK else "reference"
        new = new_note(out, "reference", title, tags, body, created)
        mapping[uid] = new.split("--")[0]
        roam_rows.append((title, new))
        report["roam"] += 1
    for _, new in roam_rows:
        s = read(new)
        s2 = re.sub(r"\[\[id:([0-9a-f-]{36})",
                    lambda m: "[[denote:" + mapping[m.group(1)] if m.group(1) in mapping else m.group(0), s)
        if s2 != s:
            with open(new, "w", encoding="utf-8") as fh:
                fh.write(s2)

    # 2. roam dailies: verbatim, dated by the file name
    for f in sorted(glob.glob(os.path.join(src, "roam", "daily", "*.org"))):
        d = os.path.basename(f)[:-4]
        s = re.sub(r"\A:PROPERTIES:\n:ID:.*\n:END:\n", "", read(f))
        _, body = strip_title(s)
        kb("new", "daily", d, "--body", body, "--created", d)
        report["dailies"] += 1

    # 3. person notes and reference notes from org/
    def org(key):
        return os.path.join(src, "org", key + ".org")
    for n in PERSONS:
        s = read(org(n))
        title, body = strip_title(s)
        new_note(out, "person", n.capitalize(), "work", body, earliest(s, org(n)))
        report["persons"] += 1
    for key, title, tags in REFERENCES:
        s = read(org(key))
        if key in WEEKDAY_FIXES:
            a, b = WEEKDAY_FIXES[key]
            assert s.count(a) == 1, key
            s = s.replace(a, b)
        _, body = strip_title(s)
        new_note(out, "reference", title, tags, body, earliest(s, org(key)))
        report["references"] += 1

    # 4. project notes, then move the open tasks out of the imported notes (a task lives in one file)
    blog = read(org("blog"))
    _, blog_body = strip_title(blog)
    blog_file = new_note(out, "project", "Blog", "personal", "", earliest(blog, org("blog")))
    with open(blog_file, "a", encoding="utf-8") as fh:
        fh.write(blog_body)
    backlog = new_note(out, "project", "Logistics backlog", "work", "", None)
    with open("tasks.org", "w", encoding="utf-8") as fh:
        fh.write("#+title: Tasks\n")
    titles = {k: t for k, t, _ in REFERENCES}
    def note_file(key):
        return glob.glob("*--%s__*.org" % re.sub(r"[^a-z0-9]+", "-", titles[key].lower()))[0]
    moved = 0
    for pairs, dest in ((BACKLOG_TASKS, [backlog, "Tasks"]), (TASKS_ORG, ["tasks.org"])):
        for key, prefix in pairs:
            srcfile = note_file(key)
            m = re.search(r"^\*+ (?:TODO|NEXT|WAITING) (" + re.escape(prefix) + r".*?)(?:[ \t]+:[\w:@]+:)?[ \t]*$",
                          read(srcfile), re.M)
            if not m:
                sys.exit("task not found: %s / %s" % (key, prefix))
            kb("refile", srcfile, m.group(1), *dest)
            moved += 1

    # 5. archive copies of the two old plain files
    os.makedirs("archive/legacy", exist_ok=True)
    for key, name in TO_ARCHIVE.items():
        shutil.copy(org(key), os.path.join("archive", "legacy", name))

    # 6. inbox note with the proposed grouping of the roam notes
    groups = {g: [] for g, _ in GROUPS}
    other = []
    for title, new in roam_rows:
        for g, rx in GROUPS:
            if re.search(rx, title.lower()):
                groups[g].append((title, new))
                break
        else:
            other.append((title, new))
    b = ("Imported %d roam notes, one note each (kept separate). Proposed groupings, to decide at triage.\n"
         "Drop candidates: Lounge, WSL2 can't connect to host, HTML (under 200 bytes, no real content).\n"
         % len(roam_rows))
    for g, items in list(groups.items()) + [("Other", other)]:
        if items:
            b += "\n* %s (%d)\n" % (g, len(items)) + "".join(
                "- [[denote:%s][%s]]\n" % (n.split("--")[0], t) for t, n in sorted(items))
    kb("new", "inbox", "--body", b)

    print(kb("sync-todo-tags"))
    print(kb("validate", "--strict", ok=True))
    print("imported:", report, "| tasks moved:", moved, "| dropped:", " ".join(DROPPED))


main()
